[settings]
experimental = true
python.uv_venv_auto = true

[env]
COVERAGE_RCFILE = "configs/.coveragerc"
TB_PROJECT_SOURCE = "pkglink"

[tools]
uv = "0.7.20"
dprint = "0.50.1"
starship = "1.23.0"

[hooks]
postinstall = [
  "uvx pkglink link github:hotdog-werx/codeguide@v0.0.2",
  "poe setup-hook",
]
