[tool.poe.tasks]

uv-sync = "uv sync --all-groups"

check-python = 'uvx tbelt check python'
check-types = 'uvx tbelt check basedpyright'
check-complexity = 'uvx tbelt check complexity'
check-coverage = 'uvx tbelt check coverage'
check-toml = 'uvx tbelt check toml'
check-prettier = 'uvx tbelt check prettier'
ci-checks.sequence = [
  'check-toml',
  'check-prettier',
  'check-python',
  'check-types',
  'check-complexity',
  'check-coverage',
]
